name: Publish Node Package (CD)

on:
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types:
      - completed
jobs:                   
  publish-npm:
    name: Publish node package.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
